"""
BGP Protocol Constants and Structures
Based on RFC 4271 specifications
"""

MARKER = b"\xff" * 16

BGP_PORT = 179

MESSAGE_TYPES = {
    "OPEN": 1,
    "UPDATE": 2,
    "NOTIFICATION": 3,
    "KEEPALIVE": 4,
    "ROUTE_REFRESH": 5,
}

MESSAGE_TYPE_NAMES = {v: k for k, v in MESSAGE_TYPES.items()}

MESSAGE_MIN_LENGTHS = {1: 29, 2: 23, 3: 21, 4: 19, 5: 23}

ORIGIN_TYPES = {"IGP": 0, "EGP": 1, "INCOMPLETE": 2}

AS_PATH_SEGMENT_TYPES = {"AS_SET": 1, "AS_SEQUENCE": 2}

PATH_ATTRIBUTE_FLAGS = {
    "OPTIONAL": 0x80,
    "TRANSITIVE": 0x40,
    "PARTIAL": 0x20,
    "EXTENDED_LENGTH": 0x10,
}

PATH_ATTRIBUTE_TYPES = {
    "ORIGIN": 1,
    "AS_PATH": 2,
    "NEXT_HOP": 3,
    "MULTI_EXIT_DISC": 4,
    "LOCAL_PREF": 5,
    "ATOMIC_AGGREGATE": 6,
    "AGGREGATOR": 7,
    "COMMUNITY": 8,
    "ORIGINATOR_ID": 9,
    "CLUSTER_LIST": 10,
    "MP_REACH_NLRI": 14,
    "MP_UNREACH_NLRI": 15,
    "AS4_AGGREGATOR": 18,
    "LARGE_COMMUNITY": 32,
}

NOTIFICATION_ERROR_CODES = {
    "MESSAGE_HEADER_ERROR": 1,
    "OPEN_MESSAGE_ERROR": 2,
    "UPDATE_MESSAGE_ERROR": 3,
    "HOLD_TIMER_EXPIRED": 4,
    "FINITE_STATE_MACHINE_ERROR": 5,
    "CEASE": 6,
}

MESSAGE_HEADER_ERROR_SUBCODES = {
    "CONNECTION_NOT_SYNCHRONIZED": 1,
    "BAD_MESSAGE_LENGTH": 2,
    "BAD_MESSAGE_TYPE": 3,
}

OPEN_MESSAGE_ERROR_SUBCODES = {
    "UNSUPPORTED_VERSION_NUMBER": 1,
    "BAD_PEER_AS": 2,
    "BAD_BGP_IDENTIFIER": 3,
    "UNSUPPORTED_OPTIONAL_PARAMETER": 4,
    "UNACCEPTABLE_HOLD_TIME": 6,
}

UPDATE_MESSAGE_ERROR_SUBCODES = {
    "MALFORMED_ATTRIBUTE_LIST": 1,
    "UNRECOGNIZED_WELL_KNOWN_ATTRIBUTE": 2,
    "MISSING_WELL_KNOWN_ATTRIBUTE": 3,
    "ATTRIBUTE_FLAGS_ERROR": 4,
    "ATTRIBUTE_LENGTH_ERROR": 5,
    "INVALID_ORIGIN_ATTRIBUTE": 6,
    "INVALID_NEXT_HOP_ATTRIBUTE": 8,
    "OPTIONAL_ATTRIBUTE_ERROR": 9,
    "INVALID_NETWORK_FIELD": 10,
    "MALFORMED_AS_PATH": 11,
}

NOTIFICATION_ERROR_SUBCODES_HOLD_TIMER = {"NO_SPECIFIC_ERROR": 0}

NOTIFICATION_ERROR_SUBCODES_FSM = {
    "UNSPECIFIED_ERROR": 0,
    "SEND_RECEIVE_UNSPECIFIED": 1,
    "SEND_RECEIVE_CONNECTION_REJECTED": 2,
    "UNEXPECTED_FSM_STATE": 3,
}

NOTIFICATION_ERROR_SUBCODES_CEASE = {
    "MAX_PREFIXES_EXCEEDED": 1,
    "ADMINISTRATIVE_SHUTDOWN": 2,
    "PEER_DECONFIGURED": 3,
    "ADMINISTRATIVE_RESET": 4,
    "CONNECTION_REJECTED": 5,
    "OTHER_CONFIGURATION_CHANGE": 6,
    "CONNECTION_COLLISION": 7,
    "OUT_OF_RESOURCES": 8,
}

WELL_KNOWN_MANDATORY_ATTRIBUTES = [1, 2, 3]
WELL_KNOWN_DISCRETIONARY_ATTRIBUTES = [5, 6, 7]

AFI_VALUES = {
    "IPv4": 1,
    "IPv6": 2,
    "NSAP": 3,
    "ISO": 5,
    "BGP_LS": 16388,
    "BGP_LS_VPN": 16389,
}

SAFI_VALUES = {
    "UNICAST": 1,
    "MULTICAST": 2,
    "UNICAST_MULTICAST": 3,
    "MPLS_VPN": 128,
    "MPLS_LABEL": 132,
    "BGP_LS": 133,
    "BGP_LS_VPN": 140,
}

CAPABILITY_CODES = {
    "MULTIPROTOCOL_EXTENSIONS": 1,
    "ROUTE_REFRESH": 2,
    "OUTBOUND_ROUTE_FILTERING": 3,
    "AS_CONFEDERATION": 4,
    "EXTENDED_NEXT_HOP": 5,
    "GRACEFUL_RESTART": 64,
    "FOUR_OCTET_AS_NUMBER": 65,
    "ENHANCED_ROUTE_REFRESH": 70,
    "ROUTE_REFRESH_CISCO": 128,
}

BGP_FSM_STATES = {
    "Idle": 0,
    "Connect": 1,
    "Active": 2,
    "OpenSent": 3,
    "OpenConfirm": 4,
    "Established": 5,
}

PATH_ATTRIBUTE_FLAGS_RFC4271 = {
    "WELL_KNOWN_TRANSITIVE": 0x40,
    "WELL_KNOWN_NON_TRANSITIVE": 0x00,
    "OPTIONAL_TRANSITIVE": 0x80,
    "OPTIONAL_NON_TRANSITIVE": 0x40,
}

AS_CONFED_PATH_SEGMENT_TYPES = {"AS_CONFED_SEQUENCE": 3, "AS_CONFED_SET": 4}

BGP_VERSIONS = {
    "BGP_V1": 1,
    "BGP_V2": 2,
    "BGP_V3": 3,
    "BGP_V4": 4,
}

LEGACY_PATH_ATTRIBUTE_TYPES_RFC1163 = {
    "ORIGIN": 1,
    "AS_PATH": 2,
    "NEXT_HOP": 3,
    "UNREACHABLE": 4,
    "INTER_AS_METRIC": 5,
}

LINK_TYPES_RFC1105 = {
    "INTERNAL": 0,
    "UP": 1,
    "DOWN": 2,
    "H_LINK": 3,
}

DIRECTION_TYPES_RFC1105 = {
    "UP": 1,
    "DOWN": 2,
    "H_LINK": 3,
    "EGP_LINK": 4,
    "INCOMPLETE": 5,
}

ERROR_SUBCODES_HOLD_TIMER_EXPIRED = {"NO_SPECIFIC_ERROR": 0}

ERROR_SUBCODES_FSM_ERROR = {
    "UNSPECIFIED_ERROR": 0,
    "SEND_RECEIVE_UNSPECIFIED": 1,
    "SEND_RECEIVE_CONNECTION_REJECTED": 2,
    "UNEXPECTED_FSM_STATE": 3,
}

ERROR_SUBCODES_CEASE = {
    "MAX_PREFIXES_EXCEEDED": 1,
    "ADMINISTRATIVE_SHUTDOWN": 2,
    "PEER_DECONFIGURED": 3,
    "ADMINISTRATIVE_RESET": 4,
    "CONNECTION_REJECTED": 5,
    "OTHER_CONFIGURATION_CHANGE": 6,
    "CONNECTION_COLLISION": 7,
    "OUT_OF_RESOURCES": 8,
}

WELL_KNOWN_COMMUNITIES = {
    "NO_EXPORT": 0xFFFFFF01,
    "NO_ADVERTISE": 0xFFFFFF02,
    "NO_EXPORT_SUBCONFED": 0xFFFFFF03,
}

COMMUNITY_ATTRIBUTE_TYPE = 8

LARGE_COMMUNITY_ATTRIBUTE_TYPE = 32

RESERVED_AS_NUMBERS = {
    "AS_ZERO": 0,
    "AS_RESERVED_16": 65535,
    "AS_MAX_32": 4294967295,
}

DAMPING_PARAMETERS = {
    "DEFAULT_CUTOFF_THRESHOLD": 2000,
    "DEFAULT_REUSE_THRESHOLD": 750,
    "DEFAULT_MAX_HOLD_TIME": 900,
    "DEFAULT_DECAY_HALF_LIFE_REACHABLE": 900,
    "DEFAULT_DECAY_HALF_LIFE_UNREACHABLE": 900,
}

AS_NUMBER_RANGES = {
    "PRIVATE_16_BIT_MIN": 64512,
    "PRIVATE_16_BIT_MAX": 65534,
    "RESERVED_16_BIT_MIN": 0,
    "RESERVED_16_BIT_MAX": 65535,
    "RESERVED_32_BIT_MIN": 4200000000,
    "RESERVED_32_BIT_MAX": 4294967295,
}

RD_TYPES = {
    "TYPE_0": 0,
    "TYPE_1": 1,
    "TYPE_2": 2,
}

RD_TYPE_0_LENGTH = 8
RD_TYPE_1_LENGTH = 8
RD_TYPE_2_LENGTH = 8
VPN_IPV4_ADDRESS_LENGTH = 12

EXTENDED_COMMUNITY_TYPES = {
    "ROUTE_TARGET": 0x0002,
    "SITE_OF_ORIGIN": 0x0003,
}

EXTENDED_COMMUNITY_SUBTYPES = {
    "TWO_OCTET_AS_SPECIFIC": 0x00,
    "IPV4_ADDRESS_SPECIFIC": 0x01,
    "FOUR_OCTET_AS_SPECIFIC": 0x02,
}

VPN_AFI_VALUES = {
    "VPN_IPV4": 1,
    "VPN_IPV6": 2,
}

VPN_SAFI_VALUES = {
    "UNICAST": 1,
    "MULTICAST": 2,
    "MPLS_VPN": 128,
}

MPLS_LABEL_MIN = 0
MPLS_LABEL_MAX = 1048575
MPLS_LABEL_IMPLICIT_NULL = 3
MPLS_LABEL_RESERVED_MIN = 0
MPLS_LABEL_RESERVED_MAX = 15

NOTIFICATION_ERROR_SUBCODES_OPEN_MESSAGE = {
    "UNSUPPORTED_VERSION_NUMBER": 1,
    "BAD_PEER_AS": 2,
    "BAD_BGP_IDENTIFIER": 3,
    "UNSUPPORTED_OPTIONAL_PARAMETER": 4,
    "UNACCEPTABLE_HOLD_TIME": 6,
}

CAPABILITY_ERROR_SUBCODES = {
    "UNSUPPORTED_CAPABILITY": 7,
}

MPLS_LABEL_SAFI = 4
MPLS_LABEL_ENCODING_LENGTH = 3
MPLS_LABEL_STACK_DEPTH_MAX = 4
MPLS_LABEL_WITHDRAWAL_VALUE = 0x800000

WELL_KNOWN_COMMUNITIES_RFC3765 = {
    "NO_EXPORT": 0xFFFFFF01,
    "NO_ADVERTISE": 0xFFFFFF02,
    "NO_EXPORT_SUBCONFED": 0xFFFFFF03,
    "NOPEER": 0xFFFFFF04,
}

NOPEER_COMMUNITY = 0xFFFFFF04

OSCILLATION_TYPES = {
    "TYPE_I": 1,
    "TYPE_II": 2,
}

MED_COMPARISON_RULES = {
    "SAME_NEIGHBORING_AS": 0,
    "NON_COMPARABLE": 255,
}

DAMPING_CALCULATION = {
    "STABILITYFIGURE_INITIAL": 0,
    "WITHDRAWAL_PENALTY": 1000,
    "READVERTISEMENT_PENALTY": 500,
    "ATTRCHANGE_PENALTY": 500,
}

CEASE_SUBCODES_RFC4486 = {
    "MAX_PREFIXES_EXCEEDED": 1,
    "ADMINISTRATIVE_SHUTDOWN": 2,
    "PEER_DECONFIGURED": 3,
    "ADMINISTRATIVE_RESET": 4,
    "CONNECTION_REJECTED": 5,
    "OTHER_CONFIGURATION_CHANGE": 6,
    "CONNECTION_COLLISION": 7,
    "OUT_OF_RESOURCES": 8,
}

VPN_IPV6_AFI_SAFI = {"AFI": 2, "SAFI": 128}

GRACEFUL_RESTART_FLAG_RESTART = 0x80
GRACEFUL_RESTART_FLAG_FORWARDING = 0x80
GRACEFUL_RESTART_CAPABILITY_CODE = 64

GTSM_TTL_EXPECTED = 255
GTSM_TTL_MIN_HOP = 254

FLOWSPEC_AFI_SAFI = {
    "IPV4_FLOWSPEC": {"AFI": 1, "SAFI": 133},
    "VPNV4_FLOWSPEC": {"AFI": 1, "SAFI": 134},
    "IPV6_FLOWSPEC": {"AFI": 2, "SAFI": 133},
    "VPNV6_FLOWSPEC": {"AFI": 2, "SAFI": 134},
}

FLOWSPEC_COMPONENT_TYPES = {
    "DESTINATION_PREFIX": 1,
    "SOURCE_PREFIX": 2,
    "IP_PROTOCOL": 3,
    "PORT": 4,
    "DESTINATION_PORT": 5,
    "SOURCE_PORT": 6,
    "ICMP_TYPE": 7,
    "ICMP_CODE": 8,
    "TCP_FLAGS": 9,
    "PACKET_LENGTH": 10,
    "DSCP": 11,
    "FRAGMENT": 12,
}

FLOWSPEC_ACTION_TYPES = {
    "TRAFFIC_RATE": 0x8006,
    "TRAFFIC_ACTION": 0x8007,
    "REDIRECT": 0x8008,
    "TRAFFIC_MARKING": 0x8009,
}

FLOWSPEC_TCP_FLAG_BITMASK = {
    "FIN": 0x01,
    "SYN": 0x02,
    "RST": 0x04,
    "PSH": 0x08,
    "ACK": 0x10,
}

FLOWSPEC_FRAGMENT_BITMASK = {
    "DF": 0x80,
    "ISF": 0x40,
    "FF": 0x20,
    "LF": 0x10,
}

FLOWSPEC_OPERATOR_FLAGS = {
    "END_OF_LIST": 0x80,
    "AND": 0x40,
    "LESS_THAN": 0x04,
    "GREATER_THAN": 0x02,
    "EQUAL": 0x01,
}

IPV6_EXTENDED_COMMUNITY_TYPE = 25
IPV6_EXTENDED_COMMUNITY_SUBTYPES = {
    "ROUTE_TARGET": 0x0002,
    "ROUTE_ORIGIN": 0x0003,
}
IPV6_EXTENDED_COMMUNITY_LENGTH = 20

RPKI_ROUTER_PDU_TYPES = {
    "SERIAL_NOTIFY": 0,
    "SERIAL_QUERY": 1,
    "RESET_QUERY": 2,
    "CACHE_RESPONSE": 3,
    "IPV4_PREFIX": 4,
    "IPV6_PREFIX": 6,
    "END_OF_DATA": 7,
    "CACHE_RESET": 8,
    "ERROR_REPORT": 10,
}

RPKI_ROUTER_ERROR_CODES = {
    "CORRUPT_DATA": 0,
    "INTERNAL_ERROR": 1,
    "NO_DATA_AVAILABLE": 2,
    "INVALID_REQUEST": 3,
    "UNSUPPORTED_VERSION": 4,
    "UNSUPPORTED_PDU_TYPE": 5,
    "WITHDRAWAL_UNKNOWN": 6,
    "DUPLICATE_ANNOUNCEMENT": 7,
}

BGP_ORIGIN_VALIDATION_STATE = {
    "NOT_FOUND": 0,
    "VALID": 1,
    "INVALID": 2,
}

AS0 = 0

BGP_LS_AFI = 16388
BGP_LS_SAFI = 71
BGP_LS_VPN_SAFI = 72

BGP_LS_NLRI_TYPES = {
    "NODE": 1,
    "LINK": 2,
    "IPV4_TOPOLOGY_PREFIX": 3,
    "IPV6_TOPOLOGY_PREFIX": 4,
}

BGP_LS_PROTOCOL_IDS = {
    "IS_IS_LEVEL_1": 1,
    "IS_IS_LEVEL_2": 2,
    "OSPFV2": 3,
    "DIRECT": 4,
    "STATIC": 5,
    "OSPFV3": 6,
}

BGP_LS_NODE_DESCRIPTOR_SUBTLVS = {
    "AUTONOMOUS_SYSTEM": 512,
    "BGP_LS_IDENTIFIER": 513,
    "OSPF_AREA_ID": 514,
    "IGP_ROUTER_ID": 515,
}

BGP_LS_LINK_DESCRIPTOR_TLVS = {
    "LINK_LOCAL_REMOTE_IDS": 258,
    "IPV4_INTERFACE": 259,
    "IPV4_NEIGHBOR": 260,
    "IPV6_INTERFACE": 261,
    "IPV6_NEIGHBOR": 262,
    "MULTI_TOPOLOGY_ID": 263,
}

BGP_LS_PREFIX_DESCRIPTOR_TLVS = {
    "MULTI_TOPOLOGY_ID": 263,
    "OSPF_ROUTE_TYPE": 264,
    "IP_REACHABILITY_INFO": 265,
}

BLACKHOLE_COMMUNITY = 0xFFFF029A
BLACKHOLE_COMMUNITY_DECIMAL = 4294967450

SHUTDOWN_COMM_MIN_LENGTH = 0
SHUTDOWN_COMM_MAX_LENGTH = 128

CEASE_SUBCODE_ADMIN_SHUTDOWN = 2
CEASE_SUBCODE_ADMIN_RESET = 4

MULTIPLE_LABELS_CAPABILITY_CODE = 8
MULTIPLE_LABELS_COUNT_UNLIMITED = 255
MULTIPLE_LABELS_COUNT_MIN = 2

WITHDRAWAL_COMPATIBILITY_VALUE = 0x800000

LARGE_COMMUNITY_FUNCTIONS = {
    "ISO_3166_1_COUNTRY": 1,
    "UN_M49_REGION": 2,
    "RELATION": 3,
    "ASN_SELECTIVE_NO_EXPORT": 4,
    "LOCATION_SELECTIVE_NO_EXPORT": 5,
    "ASN_PREPEND": 6,
    "LOCATION_PREPEND": 7,
    "PREF_NORMAL_CUSTOMER": 8,
    "PREF_BACKUP_CUSTOMER": 9,
    "PREF_PEERING": 10,
    "PREF_TRANSIT": 11,
    "PREF_FALLBACK": 12,
}

ROUTE_SERVER_GLOBAL_ADMIN = 64511
ROUTE_SERVER_DEFAULT_NO_EXPORT = 0
ROUTE_SERVER_DEFAULT_ANNOUNCE_ALL = 0

PRIVATE_ASN_DATACENTER = {
    "MIN_16_BIT": 64512,
    "MAX_16_BIT": 65534,
}

ECMP_CAPABILITIES = {
    "BASIC_ECMP": 1,
    "MULTIPATH_RELAX": 2,
    "LINK_BANDWIDTH": 3,
}
