"""
BGP Protocol Constants and Structures
Based on RFC 4271 specifications
"""

MARKER = b"\xff" * 16

BGP_PORT = 179

MESSAGE_TYPES = {
    "OPEN": 1,
    "UPDATE": 2,
    "NOTIFICATION": 3,
    "KEEPALIVE": 4,
    "ROUTE_REFRESH": 5,
}

MESSAGE_TYPE_NAMES = {v: k for k, v in MESSAGE_TYPES.items()}

MESSAGE_MIN_LENGTHS = {1: 29, 2: 23, 3: 21, 4: 19, 5: 23}

ORIGIN_TYPES = {"IGP": 0, "EGP": 1, "INCOMPLETE": 2}

AS_PATH_SEGMENT_TYPES = {"AS_SET": 1, "AS_SEQUENCE": 2}

PATH_ATTRIBUTE_FLAGS = {
    "OPTIONAL": 0x80,
    "TRANSITIVE": 0x40,
    "PARTIAL": 0x20,
    "EXTENDED_LENGTH": 0x10,
}

PATH_ATTRIBUTE_TYPES = {
    "ORIGIN": 1,
    "AS_PATH": 2,
    "NEXT_HOP": 3,
    "MULTI_EXIT_DISC": 4,
    "LOCAL_PREF": 5,
    "ATOMIC_AGGREGATE": 6,
    "AGGREGATOR": 7,
    "COMMUNITY": 8,
    "ORIGINATOR_ID": 9,
    "CLUSTER_LIST": 10,
    "MP_REACH_NLRI": 14,
    "MP_UNREACH_NLRI": 15,
    "AS4_AGGREGATOR": 18,
    "LARGE_COMMUNITY": 32,
}

NOTIFICATION_ERROR_CODES = {
    "MESSAGE_HEADER_ERROR": 1,
    "OPEN_MESSAGE_ERROR": 2,
    "UPDATE_MESSAGE_ERROR": 3,
    "HOLD_TIMER_EXPIRED": 4,
    "FINITE_STATE_MACHINE_ERROR": 5,
    "CEASE": 6,
}

MESSAGE_HEADER_ERROR_SUBCODES = {
    "CONNECTION_NOT_SYNCHRONIZED": 1,
    "BAD_MESSAGE_LENGTH": 2,
    "BAD_MESSAGE_TYPE": 3,
}

OPEN_MESSAGE_ERROR_SUBCODES = {
    "UNSUPPORTED_VERSION_NUMBER": 1,
    "BAD_PEER_AS": 2,
    "BAD_BGP_IDENTIFIER": 3,
    "UNSUPPORTED_OPTIONAL_PARAMETER": 4,
    "UNACCEPTABLE_HOLD_TIME": 6,
}

UPDATE_MESSAGE_ERROR_SUBCODES = {
    "MALFORMED_ATTRIBUTE_LIST": 1,
    "UNRECOGNIZED_WELL_KNOWN_ATTRIBUTE": 2,
    "MISSING_WELL_KNOWN_ATTRIBUTE": 3,
    "ATTRIBUTE_FLAGS_ERROR": 4,
    "ATTRIBUTE_LENGTH_ERROR": 5,
    "INVALID_ORIGIN_ATTRIBUTE": 6,
    "INVALID_NEXT_HOP_ATTRIBUTE": 8,
    "OPTIONAL_ATTRIBUTE_ERROR": 9,
    "INVALID_NETWORK_FIELD": 10,
    "MALFORMED_AS_PATH": 11,
}

NOTIFICATION_ERROR_SUBCODES_HOLD_TIMER = {"NO_SPECIFIC_ERROR": 0}

NOTIFICATION_ERROR_SUBCODES_FSM = {
    "UNSPECIFIED_ERROR": 0,
    "SEND_RECEIVE_UNSPECIFIED": 1,
    "SEND_RECEIVE_CONNECTION_REJECTED": 2,
    "UNEXPECTED_FSM_STATE": 3,
}

NOTIFICATION_ERROR_SUBCODES_CEASE = {
    "MAX_PREFIXES_EXCEEDED": 1,
    "ADMINISTRATIVE_SHUTDOWN": 2,
    "PEER_DECONFIGURED": 3,
    "ADMINISTRATIVE_RESET": 4,
    "CONNECTION_REJECTED": 5,
    "OTHER_CONFIGURATION_CHANGE": 6,
    "CONNECTION_COLLISION": 7,
    "OUT_OF_RESOURCES": 8,
}

WELL_KNOWN_MANDATORY_ATTRIBUTES = [1, 2, 3]
WELL_KNOWN_DISCRETIONARY_ATTRIBUTES = [5, 6, 7]

AFI_VALUES = {
    "IPv4": 1,
    "IPv6": 2,
    "NSAP": 3,
    "ISO": 5,
    "BGP_LS": 16388,
    "BGP_LS_VPN": 16389,
}

SAFI_VALUES = {
    "UNICAST": 1,
    "MULTICAST": 2,
    "UNICAST_MULTICAST": 3,
    "MPLS_VPN": 128,
    "MPLS_LABEL": 132,
    "BGP_LS": 133,
    "BGP_LS_VPN": 140,
}

CAPABILITY_CODES = {
    "MULTIPROTOCOL_EXTENSIONS": 1,
    "ROUTE_REFRESH": 2,
    "OUTBOUND_ROUTE_FILTERING": 3,
    "AS_CONFEDERATION": 4,
    "EXTENDED_NEXT_HOP": 5,
    "GRACEFUL_RESTART": 64,
    "FOUR_OCTET_AS_NUMBER": 65,
    "ENHANCED_ROUTE_REFRESH": 70,
    "ROUTE_REFRESH_CISCO": 128,
}

BGP_FSM_STATES = {
    "Idle": 0,
    "Connect": 1,
    "Active": 2,
    "OpenSent": 3,
    "OpenConfirm": 4,
    "Established": 5,
}

PATH_ATTRIBUTE_FLAGS_RFC4271 = {
    "WELL_KNOWN_TRANSITIVE": 0x40,
    "WELL_KNOWN_NON_TRANSITIVE": 0x00,
    "OPTIONAL_TRANSITIVE": 0x80,
    "OPTIONAL_NON_TRANSITIVE": 0x40,
}

AS_CONFED_PATH_SEGMENT_TYPES = {"AS_CONFED_SEQUENCE": 3, "AS_CONFED_SET": 4}

BGP_VERSIONS = {
    "BGP_V1": 1,
    "BGP_V2": 2,
    "BGP_V3": 3,
    "BGP_V4": 4,
}

LEGACY_PATH_ATTRIBUTE_TYPES_RFC1163 = {
    "ORIGIN": 1,
    "AS_PATH": 2,
    "NEXT_HOP": 3,
    "UNREACHABLE": 4,
    "INTER_AS_METRIC": 5,
}

LINK_TYPES_RFC1105 = {
    "INTERNAL": 0,
    "UP": 1,
    "DOWN": 2,
    "H_LINK": 3,
}

DIRECTION_TYPES_RFC1105 = {
    "UP": 1,
    "DOWN": 2,
    "H_LINK": 3,
    "EGP_LINK": 4,
    "INCOMPLETE": 5,
}

ERROR_SUBCODES_HOLD_TIMER_EXPIRED = {"NO_SPECIFIC_ERROR": 0}

ERROR_SUBCODES_FSM_ERROR = {
    "UNSPECIFIED_ERROR": 0,
    "SEND_RECEIVE_UNSPECIFIED": 1,
    "SEND_RECEIVE_CONNECTION_REJECTED": 2,
    "UNEXPECTED_FSM_STATE": 3,
}

ERROR_SUBCODES_CEASE = {
    "MAX_PREFIXES_EXCEEDED": 1,
    "ADMINISTRATIVE_SHUTDOWN": 2,
    "PEER_DECONFIGURED": 3,
    "ADMINISTRATIVE_RESET": 4,
    "CONNECTION_REJECTED": 5,
    "OTHER_CONFIGURATION_CHANGE": 6,
    "CONNECTION_COLLISION": 7,
    "OUT_OF_RESOURCES": 8,
}

WELL_KNOWN_COMMUNITIES = {
    "NO_EXPORT": 0xFFFFFF01,
    "NO_ADVERTISE": 0xFFFFFF02,
    "NO_EXPORT_SUBCONFED": 0xFFFFFF03,
}

COMMUNITY_ATTRIBUTE_TYPE = 8

LARGE_COMMUNITY_ATTRIBUTE_TYPE = 32

RESERVED_AS_NUMBERS = {
    "AS_ZERO": 0,
    "AS_RESERVED_16": 65535,
    "AS_MAX_32": 4294967295,
}

DAMPING_PARAMETERS = {
    "DEFAULT_CUTOFF_THRESHOLD": 2000,
    "DEFAULT_REUSE_THRESHOLD": 750,
    "DEFAULT_MAX_HOLD_TIME": 900,
    "DEFAULT_DECAY_HALF_LIFE_REACHABLE": 900,
    "DEFAULT_DECAY_HALF_LIFE_UNREACHABLE": 900,
}

AS_NUMBER_RANGES = {
    "PRIVATE_16_BIT_MIN": 64512,
    "PRIVATE_16_BIT_MAX": 65534,
    "RESERVED_16_BIT_MIN": 0,
    "RESERVED_16_BIT_MAX": 65535,
    "RESERVED_32_BIT_MIN": 4200000000,
    "RESERVED_32_BIT_MAX": 4294967295,
}

RD_TYPES = {
    "TYPE_0": 0,
    "TYPE_1": 1,
    "TYPE_2": 2,
}

RD_TYPE_0_LENGTH = 8
RD_TYPE_1_LENGTH = 8
RD_TYPE_2_LENGTH = 8
VPN_IPV4_ADDRESS_LENGTH = 12

EXTENDED_COMMUNITY_TYPES = {
    "ROUTE_TARGET": 0x0002,
    "SITE_OF_ORIGIN": 0x0003,
}

EXTENDED_COMMUNITY_SUBTYPES = {
    "TWO_OCTET_AS_SPECIFIC": 0x00,
    "IPV4_ADDRESS_SPECIFIC": 0x01,
    "FOUR_OCTET_AS_SPECIFIC": 0x02,
}

VPN_AFI_VALUES = {
    "VPN_IPV4": 1,
    "VPN_IPV6": 2,
}

VPN_SAFI_VALUES = {
    "UNICAST": 1,
    "MULTICAST": 2,
    "MPLS_VPN": 128,
}

MPLS_LABEL_MIN = 0
MPLS_LABEL_MAX = 1048575
MPLS_LABEL_IMPLICIT_NULL = 3
MPLS_LABEL_RESERVED_MIN = 0
MPLS_LABEL_RESERVED_MAX = 15

NOTIFICATION_ERROR_SUBCODES_OPEN_MESSAGE = {
    "UNSUPPORTED_VERSION_NUMBER": 1,
    "BAD_PEER_AS": 2,
    "BAD_BGP_IDENTIFIER": 3,
    "UNSUPPORTED_OPTIONAL_PARAMETER": 4,
    "UNACCEPTABLE_HOLD_TIME": 6,
}

CAPABILITY_ERROR_SUBCODES = {
    "UNSUPPORTED_CAPABILITY": 7,
}

MPLS_LABEL_SAFI = 4
MPLS_LABEL_ENCODING_LENGTH = 3
MPLS_LABEL_STACK_DEPTH_MAX = 4
MPLS_LABEL_WITHDRAWAL_VALUE = 0x800000

WELL_KNOWN_COMMUNITIES_RFC3765 = {
    "NO_EXPORT": 0xFFFFFF01,
    "NO_ADVERTISE": 0xFFFFFF02,
    "NO_EXPORT_SUBCONFED": 0xFFFFFF03,
    "NOPEER": 0xFFFFFF04,
}

NOPEER_COMMUNITY = 0xFFFFFF04

OSCILLATION_TYPES = {
    "TYPE_I": 1,
    "TYPE_II": 2,
}

MED_COMPARISON_RULES = {
    "SAME_NEIGHBORING_AS": 0,
    "NON_COMPARABLE": 255,
}

DAMPING_CALCULATION = {
    "STABILITYFIGURE_INITIAL": 0,
    "WITHDRAWAL_PENALTY": 1000,
    "READVERTISEMENT_PENALTY": 500,
    "ATTRCHANGE_PENALTY": 500,
}
